services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend_name
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    container_name: db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5433:5432"

  minio:
    image: minio/minio:latest
    container_name: minio_name
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  createbucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc mb myminio/storage || true;
        mc anonymous set download myminio/storage;
      "

volumes:
  postgres_data:
  minio_data: